# 全局配置
spring:
  profiles:
    active: test
  servlet:
    multipart:
      max-file-size: 100MB  #单次上传文件最大不超过100MB
      max-request-size: 300MB  #文件总上传大小不超过300MB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        min-idle: 0
        max-idle: 10
    timeout: 1000
  session:
    store-type: redis
    timeout: 86400
  jackson:
    time-zone: Asia/Shanghai

logging:
  config: classpath:log4j2.xml
  level:
    root: INFO
    javax.activation: info
    org.apache.catalina: INFO
    org.apache.commons.beanutils.converters: INFO
    org.apache.coyote.http11.Http11Processor: INFO
    org.apache.http: INFO
    org.apache.tomcat: INFO
    org.springframework: INFO
    com.chinamobile.cmss.bdpaas.resource.monitor: DEBUG

# 修改tomcat默认端口
server:
  port: 8084