# 测试环境配置
spring:
  datasource:
    url: jdbc:mysql://124.222.60.144:3663/pet_hospital?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: zcy
    password: zcy123456
    driver-class-name: com.mysql.cj.jdbc.Driver